# Generated by Django 2.2.14 on 2020-07-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhumansmember',
            name='oh_deauth',
            field=models.BooleanField(default=False),
        ),
    ]
